# Generated by Django 5.2.17 on 2026-09-23 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('article', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('min_order', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('pack_multiple', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('purchase_to_stock_factor', models.DecimalField(decimal_places=3, default=1, max_digits=16)),
            ],
            options={
                'ordering': ['supplier__name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('warehouse', models.CharField(max_length=100)),
                ('allow_estimated_stock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('source_batches', models.JSONField(default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.supplier'),
        ),
        migrations.CreateModel(
            name='PlanningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=80)),
                ('lead_days', models.PositiveIntegerField()),
                ('review_days', models.PositiveIntegerField()),
                ('safety_days', models.PositiveIntegerField()),
                ('max_growth', models.DecimalField(decimal_places=3, default='0.300', max_digits=5)),
                ('confirmed', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('as_of', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(default=list)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.supplier')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('opening_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'month'), name='unique_monthly_stock')],
            },
        ),
        migrations.CreateModel(
            name='MonthlySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('reported', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'month'), name='unique_monthly_sale')],
            },
        ),
        migrations.CreateModel(
            name='InboundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=160)),
                ('eta', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'eta'], name='planner_inb_product_787584_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('final_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('urgency', models.CharField(default='normal', max_length=20)),
                ('explanation', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('blockers', models.JSONField(default=list)),
                ('changed_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='planner.calculationrun')),
            ],
            options={
                'ordering': ['product__sku'],
                'constraints': [models.UniqueConstraint(fields=('run', 'product'), name='unique_run_product')],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_at', models.DateTimeField()),
                ('document', models.CharField(max_length=80)),
                ('document_type', models.CharField(blank=True, max_length=80)),
                ('warehouse', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('customer_hash', models.CharField(blank=True, max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'sold_at'], name='planner_sal_product_c62221_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100)),
                ('as_of', models.DateField()),
                ('on_hand', models.DecimalField(decimal_places=3, max_digits=18)),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('free', models.DecimalField(decimal_places=3, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse', 'as_of'), name='unique_stock_snapshot')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('supplier', 'sku'), name='unique_supplier_sku'),
        ),
        migrations.AddConstraint(
            model_name='planningpolicy',
            constraint=models.UniqueConstraint(fields=('supplier', 'category'), name='unique_supplier_category_policy'),
        ),
    ]
