# Generated by Django 5.2.17 on 2026-09-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_conversion',
            field=models.BooleanField(default=False),
        ),
    ]
