# Generated by Django 5.2.17 on 2026-09-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_product_requires_conversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationrun',
            options={'permissions': [('can_approve_order', 'Can approve supplier orders')]},
        ),
    ]
