# Generated by Django 5.2.17 on 2026-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_calculationrun_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
