# Generated by Django 5.2.17 on 2026-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_calculationrun_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
